// ========== CONFIG ==========
// Read API_URL injected at build time via env.js (generated by scripts/generate-env.js)
const API_URL =
	(window.__ENV && window.__ENV.API_URL) || 'http://localhost:5000';
const API = {
	AUTH: {
		REGISTER: `${API_URL}/api/auth/register`,
		LOGIN: `${API_URL}/api/auth/login`,
		LOGOUT: `${API_URL}/api/auth/logout`,
		ME: `${API_URL}/api/auth/me`,
	},
	BOOKS: {
		GET_ALL: `${API_URL}/api/books`,
		GET_ONE: (id) => `${API_URL}/api/books/${id}`,
		SEARCH: `${API_URL}/api/books/search`,
	},
	CART: {
		GET: `${API_URL}/api/cart`,
		ADD: `${API_URL}/api/cart/items`,
		UPDATE: (id) => `${API_URL}/api/cart/items/${id}`,
		REMOVE: (id) => `${API_URL}/api/cart/items/${id}`,
		CLEAR: `${API_URL}/api/cart`,
	},
	ORDERS: {
		CREATE: `${API_URL}/api/orders`,
		GET_ALL: `${API_URL}/api/orders`,
		GET_ONE: (id) => `${API_URL}/api/orders/${id}`,
	},
	PAYMENT: {
		INIT_ESEWA: (orderId) => `${API_URL}/api/payment/esewa/init/${orderId}`,
		CHECK_STATUS: (orderId) => `${API_URL}/api/payment/esewa/status/${orderId}`,
	},
};

// ========== STATE ==========
let currentUser = null;
let cart = [];
let books = [];

// ========== API HELPER ==========
async function apiCall(endpoint, options = {}) {
	const config = {
		...options,
		credentials: 'include',
		headers: {
			'Content-Type': 'application/json',
			...(options.headers || {}),
		},
	};

	const res = await fetch(endpoint, config);
	const data = await res.json();

	if (!res.ok) {
		throw new Error(data.error || data.message || 'API Error');
	}

	return data;
}

// ========== AUTH FUNCTIONS ==========
async function register() {
	const name = document.getElementById('regName').value;
	const email = document.getElementById('regEmail').value;
	const password = document.getElementById('regPassword').value;

	if (!name || !email || !password) {
		showToast('Please fill all fields', 'error');
		return;
	}

	try {
		await apiCall(API.AUTH.REGISTER, {
			method: 'POST',
			body: JSON.stringify({ name, email, password }),
		});

		showToast('Registration successful! Please login.', 'success');
		switchForm('login');
	} catch (err) {
		showToast(err.message, 'error');
	}
}

async function login() {
	const email = document.getElementById('loginEmail').value;
	const password = document.getElementById('loginPassword').value;

	if (!email || !password) {
		showToast('Please fill all fields', 'error');
		return;
	}

	try {
		const data = await apiCall(API.AUTH.LOGIN, {
			method: 'POST',
			body: JSON.stringify({ email, password }),
		});

		currentUser = data.user;
		showToast('Login successful!', 'success');
		showApp();
		loadBooks();
	} catch (err) {
		showToast(err.message, 'error');
	}
}

async function logout() {
	try {
		await apiCall(API.AUTH.LOGOUT, { method: 'POST' });
		currentUser = null;
		cart = [];
		document.getElementById('cartCount').textContent = '0';
		showAuth();
		showToast('Logged out', 'success');
	} catch (err) {
		showToast(err.message, 'error');
	}
}

function switchForm(form) {
	document.getElementById('loginForm').style.display =
		form === 'login' ? 'block' : 'none';
	document.getElementById('registerForm').style.display =
		form === 'register' ? 'block' : 'none';
}

// ========== UI FUNCTIONS ==========
function showAuth() {
	document.getElementById('authSection').style.display = 'flex';
	document.getElementById('appSection').style.display = 'none';
	document.getElementById('logoutBtn').style.display = 'none';
	switchForm('login');
}

function showApp() {
	document.getElementById('authSection').style.display = 'none';
	document.getElementById('appSection').style.display = 'block';
	document.getElementById('logoutBtn').style.display = 'block';
	switchView('books');
}

function switchView(view) {
	document.getElementById('booksView').style.display =
		view === 'books' ? 'block' : 'none';
	document.getElementById('cartView').style.display =
		view === 'cart' ? 'block' : 'none';
	document.getElementById('ordersView').style.display =
		view === 'orders' ? 'block' : 'none';

	if (view === 'cart') {
		loadCart();
	} else if (view === 'orders') {
		loadOrders();
	}
}

function showToast(msg, type = 'info') {
	const toast = document.getElementById('toast');
	toast.textContent = msg;
	toast.className = `toast show ${type}`;
	setTimeout(() => {
		toast.classList.remove('show');
	}, 3000);
}

// ========== BOOKS ==========
async function loadBooks() {
	const grid = document.getElementById('booksList');
	grid.innerHTML = '<p style="text-align:center; padding:40px;">Loading...</p>';

	try {
		const data = await apiCall(API.BOOKS.GET_ALL);
		books = data.books || [];
		displayBooks();
	} catch (err) {
		grid.innerHTML = `<p style="text-align:center; padding:40px; color:red;">${err.message}</p>`;
	}
}

function displayBooks() {
	const grid = document.getElementById('booksList');

	if (!books.length) {
		grid.innerHTML =
			'<p style="text-align:center; padding:40px;">No books found</p>';
		return;
	}

	grid.innerHTML = books
		.map(
			(book) => `
		<div class="book-card">
			<div class="book-image">📕</div>
			<div class="book-info">
				<div class="book-title">${book.title}</div>
				<div class="book-author">${book.author}</div>
				<div class="book-price">Rs. ${book.price}</div>
				<button onclick="addToCart('${book._id}')">Add to Cart</button>
			</div>
		</div>
	`
		)
		.join('');
}

async function addToCart(bookId) {
	try {
		await apiCall(API.CART.ADD, {
			method: 'POST',
			body: JSON.stringify({ bookId, quantity: 1 }),
		});
		updateCartCount();
		showToast('Added to cart!', 'success');
	} catch (err) {
		showToast(err.message, 'error');
	}
}

// Search functionality
document.addEventListener('DOMContentLoaded', () => {
	document.getElementById('searchInput').addEventListener('keypress', (e) => {
		if (e.key === 'Enter') {
			const query = e.target.value.trim();
			if (query) {
				searchBooks(query);
			}
		}
	});
});

async function searchBooks(query) {
	const grid = document.getElementById('booksList');
	grid.innerHTML =
		'<p style="text-align:center; padding:40px;">Searching...</p>';

	try {
		const data = await apiCall(
			`${API.BOOKS.SEARCH}?query=${encodeURIComponent(query)}`
		);
		books = data.data || [];
		displayBooks();
	} catch (err) {
		showToast(err.message, 'error');
		loadBooks();
	}
}

// ========== CART ==========
async function loadCart() {
	try {
		const data = await apiCall(API.CART.GET);
		cart = data.cart;
		displayCart();
	} catch (err) {
		showToast(err.message, 'error');
	}
}

function displayCart() {
	const list = document.getElementById('cartItemsList');

	if (!cart.items || !cart.items.length) {
		list.innerHTML =
			'<p style="text-align:center; padding:40px;">Cart is empty</p>';
		document.getElementById('checkoutBtn').disabled = true;
		document.getElementById('totalPrice').textContent = '0';
		return;
	}

	list.innerHTML = cart.items
		.map(
			(item) => `
		<div class="cart-item">
			<div class="cart-item-image">📕</div>
			<div class="cart-item-info">
				<div class="cart-item-title">${item.bookId.title}</div>
				<div class="cart-item-author">${item.bookId.author}</div>
				<div class="cart-item-price">Rs. ${item.price}</div>
				<div class="cart-item-quantity">
					Qty: <span>${item.quantity}</span>
					<button onclick="updateQty('${item.bookId._id}', ${
				item.quantity - 1
			})">-</button>
					<button onclick="updateQty('${item.bookId._id}', ${
				item.quantity + 1
			})">+</button>
				</div>
			</div>
			<div class="cart-item-actions">
				<button class="btn btn-danger btn-small" onclick="removeFromCart('${
					item.bookId._id
				}')">Remove</button>
			</div>
		</div>
	`
		)
		.join('');

	document.getElementById('totalPrice').textContent = (cart.total || 0).toFixed(
		2
	);
	document.getElementById('checkoutBtn').disabled = false;
}

async function updateQty(bookId, newQty) {
	if (newQty < 1) {
		removeFromCart(bookId);
		return;
	}

	try {
		await apiCall(API.CART.UPDATE(bookId), {
			method: 'PUT',
			body: JSON.stringify({ quantity: newQty }),
		});
		loadCart();
		updateCartCount();
	} catch (err) {
		showToast(err.message, 'error');
	}
}

async function removeFromCart(bookId) {
	try {
		await apiCall(API.CART.REMOVE(bookId), { method: 'DELETE' });
		loadCart();
		updateCartCount();
		showToast('Removed from cart', 'success');
	} catch (err) {
		showToast(err.message, 'error');
	}
}

async function updateCartCount() {
	try {
		const data = await apiCall(API.CART.GET);
		const count = (data.cart.items || []).length;
		console.log('[CartCount] Updated count:', count, 'Items:', data.cart.items);
		document.getElementById('cartCount').textContent = count;
	} catch (err) {
		console.error('[CartCount] Failed to update cart count:', err);
	}
}

// ========== CHECKOUT ==========
async function checkout() {
	console.log('=== CHECKOUT FUNCTION CALLED ===');
	console.log('[Checkout] Starting checkout process...');

	// Open a new tab synchronously to avoid popup blocking
	const popupName = `esewa_${Date.now()}`;
	const paymentWindow = window.open('', popupName);
	console.log('[Checkout] Popup opened:', paymentWindow ? 'success' : 'failed');

	try {
		// Provide user feedback in the popup immediately
		if (paymentWindow && paymentWindow.document) {
			paymentWindow.document.write(
				'<p style="font-family: sans-serif;">Preparing payment... Please wait.</p>'
			);
		}

		console.log('[Checkout] Creating order...');
		const data = await apiCall(API.ORDERS.CREATE, { method: 'POST' });
		const orderId = data.data._id;
		console.log('[Checkout] Order created with ID:', orderId);

		showToast('Order created! Initializing payment...', 'success');

		// Call payment init endpoint (returns paymentUrl + signed params) via apiCall
		console.log(
			'[Checkout] Calling payment init endpoint:',
			API.PAYMENT.INIT_ESEWA(orderId)
		);
		const initResp = await apiCall(API.PAYMENT.INIT_ESEWA(orderId), {
			method: 'POST',
		});
		console.log('[Checkout] Init response received:', initResp);

		if (!initResp.success) throw new Error('Payment init failed');

		const { paymentUrl, params } = initResp;
		console.log('[Checkout] Payment URL:', paymentUrl);
		console.log('[Checkout] Params:', params);

		// Build a form with returned params and submit to external paymentUrl in the popup
		const form = document.createElement('form');
		form.method = 'POST';
		form.action = paymentUrl;
		form.style.display = 'none';
		form.target = popupName; // submit into the previously opened tab

		// append hidden fields from params
		Object.entries(params || {}).forEach(([k, v]) => {
			const input = document.createElement('input');
			input.type = 'hidden';
			input.name = k;
			input.value = String(v ?? '');
			form.appendChild(input);
		});

		console.log('[Checkout] Submitting form to:', paymentUrl);
		document.body.appendChild(form);
		form.submit();
		// cleanup
		document.body.removeChild(form);
		console.log('[Checkout] Form submitted successfully');
	} catch (err) {
		console.error('[Checkout] Error:', err);
		showToast(err.message || 'Payment initialization failed', 'error');
		// Close the popup if it was opened and error occurred
		try {
			if (paymentWindow && !paymentWindow.closed) paymentWindow.close();
		} catch (e) {
			/* ignore */
		}
	}
}

// ========== ORDERS ==========
async function loadOrders() {
	try {
		const data = await apiCall(API.ORDERS.GET_ALL);
		displayOrders(data.data || []);
	} catch (err) {
		showToast(err.message, 'error');
	}
}

function displayOrders(orders) {
	const list = document.getElementById('ordersList');

	if (!orders.length) {
		list.innerHTML =
			'<p style="text-align:center; padding:40px;">No orders yet</p>';
		return;
	}

	list.innerHTML = orders
		.map(
			(order) => `
		<div class="order-card">
			<div class="order-header">
				<div class="order-id">Order: ${order._id.slice(-8)}</div>
				<div class="order-status ${order.status}">${order.status.toUpperCase()}</div>
			</div>
			<div>
				${order.items
					.map(
						(item) =>
							`<div class="order-item">${item.quantity}x ${
								item.bookId?.title || 'Item'
							}</div>`
					)
					.join('')}
			</div>
			<div class="order-total">Total: Rs. ${order.totalAmount}</div>
		</div>
	`
		)
		.join('');
}

// ========== NAV BUTTONS ==========
document
	.getElementById('cartBtn')
	.addEventListener('click', () => switchView('cart'));
document
	.getElementById('ordersBtn')
	.addEventListener('click', () => switchView('orders'));
document.getElementById('profileBtn').addEventListener('click', () => {
	if (currentUser) {
		showToast(`Logged in as: ${currentUser.name}`, 'info');
	}
});

document.getElementById('logoutBtn').addEventListener('click', logout);
document.getElementById('loginBtn').addEventListener('click', login);
document.getElementById('registerBtn').addEventListener('click', register);
document.getElementById('checkoutBtn').addEventListener('click', checkout);

// ========== INIT ==========
async function initApp() {
	try {
		console.log('[Init] Starting app initialization...');
		// Check if user is already logged in via cookie
		const userData = await apiCall(API.AUTH.ME);
		console.log('[Init] Auth check response:', userData);
		if (userData.user) {
			console.log('[Init] User found:', userData.user);
			currentUser = userData.user;
			await loadBooks();
			await loadCart();
			await loadOrders();
			await updateCartCount();
			showApp();
		} else {
			console.log('[Init] No user found, showing auth screen');
			showAuth();
		}
	} catch (err) {
		// User not logged in, show auth screen
		console.error('[Init] Error checking auth:', err);
		showAuth();
	}
}

initApp();
